package Enumeration;

public enum MessageType {
    JOIN_MESSAGE,
    PONG_MESSAGE,
    LEAVE_MESSAGE,
    PROPOSE_JOB,
    DUMB_MESSAGE,
    UPDATE_TABLE_MESSAGE,
    RESULT_REQUEST_MESSAGE,
    RESULT_RESPONSE_MESSAGE,
    FORWARDED_MESSAGE
}
